name: view-caller
version: 1
dependencies:
  '@types/react': ^18
  '@types/react-dom': ^18
  react: ^18
  react-dom: ^18
  web3: ^4.14.0
devDependencies:
  esbuild: ^0.24.0
  typescript: ^4
scripts:
  build: >-
    prettier --write *.html *.tsx tsconfig.json && pnpm tsc && pnpm esbuild
    --bundle main.js --outfile=index.js
